### ISSUE TITLE
Event will not move to the trash if I remove from API.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wpem-rest-api#2]
I can see the event will directly remove from the database if I delete from API. We have to move in the trash.

**Comment by hiteshmakvana** [comment]
Delete event not implemented in mobile app yet.

**Comment by hiteshmakvana** [comment]
'force' already given in API to bypass the trash or not.

**Comment by krinaydhanani** [comment]
We are not providing this feature in the current version. We will implement in future so I move this issue to the enhancement.

**Comment by iamakram22** [comment]
We need to use the parameter **`?action=trash`** to move the event to trash rather than delete it completely from the database (no need to use force parameter)

The following event is in the trash as its slug changed in the database to trashed which WordPress use to trash a post.

![image](https://github.com/wpeventmanager/wpem-rest-api/assets/55661376/4792e6cd-c84b-4299-b020-b34e6d237de9)

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now this issue is fixed.

After the event is not removed from the database if I delete it from API. Now event has to move into the trash.

So I closed the issue.
