### ISSUE TITLE
When writing a note in the app error message is display

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-rest-api#71]
When writing a note in the app error message is display.

https://www.voluntariosautomovilismo.com/wp-admin/?wtlwp_token=fa539c25a1775189abbfc24e31104cafedfeb6d2647f13baaf88d6cbd54b38c50e1d896e8dfe0856a10a42869c411065625f315a1447ca8af1912da8198fdc1e

Verified this issue. First I have login in the app and checked here rest api not supported message is display. 

URL -https://www.voluntariosautomovilismo.com/

key - 1341080619

**Comment by ritakikani** [comment]
This issue is occur when user logged in as "Organizer". If user loggedIn as "Administrator" then user can add Note.
In short in Rest Api permission is checked for loggedin user to read/write operation. Only administrator can write post/comment. Organizer has only read permission. 

In our Core plusin, when we install plugin at that time Organizer Role is created and there only read permission is given to organizer.

So for further changes in Organizer permission, need to discuss.

**Comment by mistry-jignesh** [comment]
Verified this issue in the admin and Organizer account.

Now When writing a note in the app then error message is not display and note is added without issue.

So I closed the issue.
