### ISSUE TITLE
Unalbe to change title name 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-rest-api#78]
Unalbe to change title name .

![image](https://user-images.githubusercontent.com/75515088/181763154-3a165028-9d77-4aa0-821b-81f823bbe18b.png)

**Comment by iamakram22** [comment]
@mistry-jignesh Application name feature added to the addon.

![image](https://github.com/wpeventmanager/wpem-rest-api/assets/55661376/9515e18b-519a-444f-acca-f98e103c42a5)

@arqummalik1 please integrate the feature into the Mobile app

**Comment by ritakikani** [comment]
Hi @iamakram22, if this issue is resolve from your side in plugin, then you have to remove label "Enahncement" and need to assign it to @mistry-jignesh to test. And you have to inform him that how it would be displayed in app, then he will open bug in git Organizer App(Mobile App) directory and will assign it to @arqummalik1 . You do not need to assign here to arqum, here you have to assign it to @mistry-jignesh only.

**Comment by arqummalik1** [comment]
if there is any issue from the mobile side, please open bug in Wp-organiser-app repo @iamakram22

**Comment by iamakram22** [comment]
as discussed with @ritakikani, removed the App name from the API access and added it in the General settings.

![image](https://github.com/wpeventmanager/wpem-rest-api/assets/55661376/18fc7f8e-2788-49af-8297-714f9e4dd0db)

**Comment by mistry-jignesh** [comment]
Verified this issue. Now this issue is fixed.

Now App name is changed.

![image](https://github.com/wpeventmanager/wpem-rest-api/assets/75515088/f2c5a707-b77e-4453-81b6-1a8012def7f4)

So I closed the issue.

**Comment by mistry-jignesh** [comment]
I have verfied this issue. Now this issue is fixed.
Now title name is changed
![image](https://github.com/wpeventmanager/wpem-rest-api/assets/75515088/738cfbc5-4e9d-470a-a6ca-79deee420bd0)
